In [1]:
import numpy as np
import pandas as pd

import os

COMPETITION_NAME = "smart-mcq-solver-challenge"

# Check if running inside Kaggle or Locally
IS_KAGGLE = "KAGGLE_KERNEL_RUN_TYPE" in os.environ

if IS_KAGGLE:
    DATA_DIR = f"/kaggle/input/competitions/{COMPETITION_NAME}"
else: #local file directory
    DATA_DIR = "./data"

trainPath = os.path.join(DATA_DIR, "train.csv")
testPath = os.path.join(DATA_DIR, "test.csv")
sampleSubmissionPath = os.path.join(DATA_DIR, "sample_submission.csv")

for dirname, _, filenames in os.walk(DATA_DIR):
    for filename in filenames:
        print(os.path.join(dirname, filename))

./data\sample_submission.csv
./data\test.csv
./data\train.csv

In [2]:
import os
import wandb

def setup_wandb():

    try:
        if os.getenv("KAGGLE_KERNEL_RUN_TYPE"):
            from kaggle_secrets import UserSecretsClient
            secrets = UserSecretsClient()
            wandb_key = secrets.get_secret(
                "WANDB_API_KEY"
            )
            wandb.login(
                key=wandb_key
            )
            print("W&B login: Kaggle Secrets")

        else:
            from dotenv import load_dotenv
            load_dotenv()
            wandb_key = os.getenv("WANDB_API_KEY")
            if wandb_key is None:
                raise ValueError("WANDB_API_KEY not found in .env")
            wandb.login(key=wandb_key)
            print("W&B login: Local .env")
        return True
    
    except Exception as error:
        print("W&B disabled:", error)
        return False

In [3]:
use_wandb = setup_wandb()

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: Appending key for api.wandb.ai to your netrc file: C:\Users\bires\_netrc
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

W&B login: Local .env

In [4]:
train = pd.read_csv(trainPath)
test = pd.read_csv(testPath)
print(f"[{'Kaggle' if IS_KAGGLE else 'Local'}] Successfully loaded data!")

[Local] Successfully loaded data!

In [5]:
if IS_KAGGLE:
    import shutil
    from kaggle_secrets import UserSecretsClient
    
    user_secrets = UserSecretsClient()
    token = user_secrets.get_secret("github_token")
    repo_name = "DL_genAI_2026"
    
    if os.path.exists(repo_name):
        shutil.rmtree(repo_name)
    
    repo_url = f"https://oauth2:{token}@github.com/Bireswar-Sett/DL_genAI_2026.git"
    exit_code = os.system(f"git clone {repo_url}")
    
    if exit_code == 0:
        os.chdir(repo_name)
        print("Succesfully cloned")
        print(os.getcwd())
    else:
        print("Failed to clone the repo")

In [6]:
train.head()

,id,prompt,A,B,C,D,E,answer
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
1,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,A
2,3,Determine the correct option: What is the term...,Blueshifting,Redshifting,Reddening,Whitening,Yellowing,C
3,4,Select the most accurate option: What is Marti...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
4,5,Identify the correct statement: What is the co...,"Simultaneity is relative, meaning that two eve...","Simultaneity is relative, meaning that two eve...","Simultaneity is absolute, meaning that two eve...",Simultaneity is a concept that applies only to...,Simultaneity is a concept that applies only to...,A

Since the `id` column is a surrogate key there's no use in keeping it for any further processing it

In [7]:
train.drop('id', axis=1, inplace=True)
test.drop('id', axis=1, inplace=True)

In [8]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   prompt  2000 non-null   str
 1   A       2000 non-null   str
 2   B       2000 non-null   str
 3   C       2000 non-null   str
 4   D       2000 non-null   str
 5   E       2000 non-null   str
 6   answer  2000 non-null   str
dtypes: str(7)
memory usage: 1.9 MB

In [9]:
train.duplicated().sum()

np.int64(183)

There are total of 183 duplicate rows. Since these might cause bias in the trainning and possible leakage we are going to remove them.

In [10]:
train.drop_duplicates(inplace=True)

In [11]:
train.info()

<class 'pandas.DataFrame'>
Index: 1817 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   prompt  1817 non-null   str
 1   A       1817 non-null   str
 2   B       1817 non-null   str
 3   C       1817 non-null   str
 4   D       1817 non-null   str
 5   E       1817 non-null   str
 6   answer  1817 non-null   str
dtypes: str(7)
memory usage: 1.8 MB

#### Checking for duplicate prompts

In [12]:
train["prompt"].duplicated().sum()

np.int64(59)

In [13]:
prompt_freq = train["prompt"].value_counts()

print(prompt_freq.value_counts().sort_index())

count
1    1704
2      49
3       5
Name: count, dtype: int64

In [14]:
# Group by prompt and check if options differ for duplicate prompts
duplicates = train[train.duplicated(subset=['prompt'], keep=False)].sort_values('prompt')
print(len(duplicates))
for prompt in duplicates['prompt'].unique():
    prompt_data = train[train['prompt'] == prompt][['A', 'B', 'C', 'D', 'E', 'answer']]
    print(f"\nPrompt: {prompt}")
    print(prompt_data.to_string())
    print("-" * 100)

113

Prompt: Choose the correct answer: What is Modified Newtonian Dynamics (MOND)? based on the given context.
                                                                                                                                                                                                                                                                     A                                                                                                                                                                                                                                                                                                          B                                                                                                                                                                                                                                                                                                     C                                                                                                                                                                                                                                                                             D                                                                                                                                                                                                                                                                                      E answer
291  MOND is a framework that explains the behavior of light in the presence of strong gravitational fields. It is an alternative to the hypothesis of dark matter in terms of explaining why galaxies do not appear to obey the currently understood laws of physics.  MOND is a hypothesis that proposes a modification of Einstein's principle of general relativity to account for observed properties of galaxies. It is an alternative to the hypothesis of dark matter in terms of explaining why galaxies do not appear to obey the currently understood laws of physics.  MOND is a hypothesis that proposes a modification of Newton's law of universal gravitation to account for observed properties of galaxies. It is an alternative to the hypothesis of dark matter in terms of explaining why galaxies do not appear to obey the currently understood laws of physics.  MOND is a hypothesis that proposes a modification of Coulomb's law to account for observed properties of galaxies. It is an alternative to the hypothesis of dark matter in terms of explaining why galaxies do not appear to obey the currently understood laws of physics.  MOND is a principle that explains the behavior of subatomic particles in the presence of strong magnetic fields. It is an alternative to the hypothesis of dark energy in terms of explaining why subatomic particles do not appear to obey the currently understood laws of physics.      C
848  MOND is a principle that explains the behavior of light in the presence of strong gravitational fields. It is an alternative to the hypothesis of dark matter in terms of explaining why galaxies do not appear to obey the currently understood laws of physics.    MOND is a hypothesis that proposes a modification of Einstein's concept of general relativity to account for observed properties of galaxies. It is an alternative to the hypothesis of dark matter in terms of explaining why galaxies do not appear to obey the currently understood laws of physics.  MOND is a hypothesis that proposes a modification of Newton's law of universal gravitation to account for observed properties of galaxies. It is an alternative to the hypothesis of dark matter in terms of explaining why galaxies do not appear to obey the currently understood laws of physics.  MOND is a hypothesis that proposes a modification of Coulomb's law to account for observed properties of galaxies. It is an alternative to the hypothesis of dark matter in terms of explaining why galaxies do not appear to obey the currently understood laws of physics.  MOND is a principle that explains the behavior of subatomic particles in the presence of strong magnetic fields. It is an alternative to the hypothesis of dark energy in terms of explaining why subatomic particles do not appear to obey the currently understood laws of physics.      C
----------------------------------------------------------------------------------------------------

Prompt: Choose the correct answer: What is a planetary mechanism? based on the given context.
                                                                             A                                                             B                                                                                                         C                                                                D                                                 E answer
162   A mechanism of planets that are all located in the same solar mechanism.  A framework of planets that are all the same size and shape.  Any set of gravitationally bound non-stellar objects in or out of orbit around a star or star mechanism.  A structure of planets that are all located in the same galaxy.  A structure of planets that are all made of gas.      C
1944  A mechanism of planets that are all located in the same solar mechanism.  A framework of planets that are all the same size and shape.  Any set of gravitationally bound non-stellar objects in or out of orbit around a star or star structure.  A framework of planets that are all located in the same galaxy.  A framework of planets that are all made of gas.      C
----------------------------------------------------------------------------------------------------

Prompt: Choose the correct answer: What is a planetary structure? based on the given context.
                                                                            A                                                             B                                                                                                         C                                                                D                                                 E answer
146  A framework of planets that are all located in the same solar framework.  A framework of planets that are all the same size and shape.  Any set of gravitationally bound non-stellar objects in or out of orbit around a star or star structure.  A mechanism of planets that are all located in the same galaxy.  A structure of planets that are all made of gas.      C
545  A mechanism of planets that are all located in the same solar mechanism.  A mechanism of planets that are all the same size and shape.  Any set of gravitationally bound non-stellar objects in or out of orbit around a star or star structure.  A framework of planets that are all located in the same galaxy.  A framework of planets that are all made of gas.      C
----------------------------------------------------------------------------------------------------

Prompt: Choose the correct answer: What is accelerator-based light-ion fusion? carefully.
                                                                                                                                                                                                                                                                                                                                                                                                                              A                                                                                                                                                                                                                                                                                                                                                                                   B                                                                                                                                                                                                                                                                                                                                                                                    C                                                                                                                                                                                                                                                                                                                                                                                                                           D                                                                                                                                                                                                                                                                                                                                                                                                                            E answer
1133  Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This procedure is relatively easy to implement and can be done in an efficient manner, requiring only a vacuum tube, a pair of electrodes, and a high-voltage transformer. Fusion can be observed with as little as 10 kV between the electrodes.  Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce heavy-ion fusion reactions. This procedure is relatively difficult to implement and requires a complex structure of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 10 kV between the electrodes.  Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This technique is relatively difficult to implement and requires a complex structure of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 100 kV between the electrodes.  Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce heavy-ion fusion reactions. This procedure is relatively easy to implement and can be done in an efficient manner, requiring only a vacuum tube, a pair of electrodes, and a high-voltage transformer. Fusion can be observed with as little as 100 kV between the electrodes.   Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fission reactions. This approach is relatively easy to implement and can be done in an efficient manner, requiring only a vacuum tube, a pair of electrodes, and a high-voltage transformer. Fission can be observed with as little as 10 kV between the electrodes.      A
1690   Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This approach is relatively easy to implement and can be done in an efficient manner, requiring only a vacuum tube, a pair of electrodes, and a high-voltage transformer. Fusion can be observed with as little as 10 kV between the electrodes.   Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce heavy-ion fusion reactions. This approach is relatively difficult to implement and requires a complex framework of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 10 kV between the electrodes.  Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This procedure is relatively difficult to implement and requires a complex framework of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 100 kV between the electrodes.   Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce heavy-ion fusion reactions. This approach is relatively easy to implement and can be done in an efficient manner, requiring only a vacuum tube, a pair of electrodes, and a high-voltage transformer. Fusion can be observed with as little as 100 kV between the electrodes.  Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fission reactions. This technique is relatively easy to implement and can be done in an efficient manner, requiring only a vacuum tube, a pair of electrodes, and a high-voltage transformer. Fission can be observed with as little as 10 kV between the electrodes.      A
----------------------------------------------------------------------------------------------------

Prompt: Choose the correct answer: What is the Maxwell's Demon thought experiment? among the listed options.
                                                                                                                                                                                                                                                                                                                                                                                         A                                                                                                                                                                                                                                                                                                                                                                                                 B                                                                                                                                                                                                                                                                                                                                                                                                       C                                                                                                                                                                                                                                                                                                                                                                                                         D                                                                                                                                                                                                                                                                                                                                                                                                                E answer
371     A thought experiment in which a demon guards a microscopic trapdoor in a wall separating two parts of a container filled with different gases at equal temperatures. The demon selectively allows molecules to pass from one side to the other, causing an raise in temperature in one part and a lower in temperature in the other, contrary to the second law of thermodynamics.  A thought experiment in which a demon guards a macroscopic trapdoor in a wall separating two parts of a container filled with different gases at different temperatures. The demon selectively allows molecules to pass from one side to the other, causing a minimize in temperature in one part and an boost in temperature in the other, in accordance with the second law of thermodynamics.    A thought experiment in which a demon guards a microscopic trapdoor in a wall separating two parts of a container filled with the same gas at equal temperatures. The demon selectively allows faster-than-average molecules to pass from one side to the other, causing a reduce in temperature in one part and an raise in temperature in the other, contrary to the second law of thermodynamics.    A thought experiment in which a demon guards a macroscopic trapdoor in a wall separating two parts of a container filled with the same gas at equal temperatures. The demon selectively allows faster-than-average molecules to pass from one side to the other, causing an enhance in temperature in one part and a reduce in temperature in the other, contrary to the second law of thermodynamics.  A thought experiment in which a demon guards a microscopic trapdoor in a wall separating two parts of a container filled with the same gas at different temperatures. The demon selectively allows slower-than-average molecules to pass from one side to the other, causing a reduce in temperature in one part and an boost in temperature in the other, in accordance with the second law of thermodynamics.      C
500   A thought experiment in which a demon guards a microscopic trapdoor in a wall separating two parts of a container filled with different gases at equal temperatures. The demon selectively allows molecules to pass from one side to the other, causing an enhance in temperature in one part and a lower in temperature in the other, contrary to the second law of thermodynamics.  A thought experiment in which a demon guards a macroscopic trapdoor in a wall separating two parts of a container filled with different gases at different temperatures. The demon selectively allows molecules to pass from one side to the other, causing a minimize in temperature in one part and an raise in temperature in the other, in accordance with the second law of thermodynamics.    A thought experiment in which a demon guards a microscopic trapdoor in a wall separating two parts of a container filled with the same gas at equal temperatures. The demon selectively allows faster-than-average molecules to pass from one side to the other, causing a reduce in temperature in one part and an raise in temperature in the other, contrary to the second law of thermodynamics.      A thought experiment in which a demon guards a macroscopic trapdoor in a wall separating two parts of a container filled with the same gas at equal temperatures. The demon selectively allows faster-than-average molecules to pass from one side to the other, causing an boost in temperature in one part and a reduce in temperature in the other, contrary to the second law of thermodynamics.  A thought experiment in which a demon guards a microscopic trapdoor in a wall separating two parts of a container filled with the same gas at different temperatures. The demon selectively allows slower-than-average molecules to pass from one side to the other, causing a reduce in temperature in one part and an raise in temperature in the other, in accordance with the second law of thermodynamics.      C

After inspection the prompts might be same, but since the options differ it can help the models learn different ways to answer a question rather than memorising or essentially overfitting. So, we will be keeping these augmented mostly synonimically different rows for better generelisaiton.

Removing extra spaces from the prompt and options columns

In [15]:
text_cols = ["prompt", "A", "B", "C", "D", "E"]

for col in text_cols:
    train[col] = (
        train[col]
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )
    test[col] = (
            test[col]
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

In [16]:
train.isnull().sum()

prompt    0
A         0
B         0
C         0
D         0
E         0
answer    0
dtype: int64

There is no null values in either of the feature columns

Mapping the label with numbers since model takes only numbers

In [17]:
mapping = {
    "A":0,
    "B":1,
    "C":2,
    "D":3,
    "E":4
}

train["label"] = train["answer"].map(mapping)

In [18]:
trainStats = pd.DataFrame()

In [19]:
trainStats["prompt"] = train['prompt'].str.split().str.len()
options = ["A","B","C","D","E"]

for col in options:
    trainStats[col] = train[col].str.split().str.len()

In [20]:
def length_bias(row):
    correct = len(row[row["answer"]].split())
    
    others = []

    for x in ["A","B","C","D","E"]:
        if x != row["answer"]:
            length = len(row[x].split())
            others.append(length)
        
        return correct - sum(others)/4

trainStats["length_difference"] = train.apply(
    length_bias,
    axis=1
)

In [21]:
trainStats.describe().T

,count,mean,std,min,25%,50%,75%,max
prompt,1817.0,18.057237,6.844080,3.00,14.00,17.0,22.0,51.00
A,1817.0,26.202532,17.113470,1.00,13.00,22.0,37.0,81.00
B,1817.0,26.539351,18.331226,1.00,12.00,23.0,36.0,118.00
C,1817.0,26.652174,17.099736,1.00,15.00,25.0,36.0,82.00
D,1817.0,26.162906,17.158592,1.00,15.00,22.0,37.0,78.00
E,1817.0,26.231701,17.613437,1.00,13.00,23.0,36.0,105.00
length_difference,1817.0,23.448404,15.178966,-0.75,12.75,22.5,32.5,84.75

In [22]:
from transformers import AutoTokenizer

tokeniser = AutoTokenizer.from_pretrained(
    "bert-base-uncased"
)

C:\Users\bires\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [23]:
token_lengths = []
word_counts = []

options = ["A", "B", "C", "D", "E"]

for index, row in train.iterrows():

    for option in options:

        text = row["prompt"] + " " + row[option]

        tokens = tokeniser(
            text,
            add_special_tokens=True,
            truncation=False
        )["input_ids"]

        token_lengths.append(len(tokens))

        word_counts.append(len(text.split()))

In [24]:
ratio = np.array(token_lengths) / np.array(word_counts)

print(ratio.mean())
print(ratio.max())

1.3609405321290475
2.75

In [25]:
token_stats = pd.DataFrame({
    "tokens": token_lengths,
    "words": word_counts
})

token_stats.describe()

            tokens        words
count  9085.000000  9085.000000
mean     59.423445    44.414970
std      23.477263    18.685559
min      14.000000     9.000000
25%      42.000000    31.000000
50%      55.000000    40.000000
75%      73.000000    55.000000
max     199.000000   148.000000

In [26]:
(token_stats["tokens"] > 128).sum()

np.int64(108)

In [27]:
(token_stats["tokens"] > 128).mean()*100

np.float64(1.1887727022564667)

# Model

In [28]:
import random
import torch
import torch.nn as nn
import torch.optim as optim
from datasets import Dataset
from sklearn.model_selection import GroupShuffleSplit
from torch.utils.data import DataLoader
from transformers import AutoTokenizer

from src.inference import generate_submission
from src.metrics import map3_metric
from src.models.bert_model import get_model as get_bert_model
from src.models.custom_model import MCQBiEncoder
from src.models.roberta_model import get_model as get_roberta_model
from src.trainer import MCQTrainer, build_custom_scheduler, build_pretrained_trainer, build_training_args

wandb_run = wandb.init(project="mcq-custom-model", name="bert-roberta-custom")
wandb.define_metric("custom/*", step_metric="custom/epoch")

W0803 01:56:15.610000 34840 torch\utils\_pytree.py:630] <enum 'KernelPreference'> is an Enum subclass and is now natively supported by torch.compile as an opaque value type. Calling register_constant() on Enum subclasses is deprecated and will be an error in a future release.
W0803 01:56:15.664000 34840 torch\utils\_pytree.py:630] <enum 'ScaleCalculationMode'> is an Enum subclass and is now natively supported by torch.compile as an opaque value type. Calling register_constant() on Enum subclasses is deprecated and will be an error in a future release.

In [29]:
def dataset_from(dataframe, tokenize, columns):
    dataset = Dataset.from_pandas(dataframe, preserve_index=False)
    dataset = dataset.map(tokenize)
    dataset.set_format(type="torch", columns=columns)
    return dataset

In [30]:
def tokenize_pretrained(row, tokenizer):
    tokenized = tokenizer(
        [row["prompt"]] * 5,
        [row[option] for option in ["A", "B", "C", "D", "E"]],
        padding="max_length",
        truncation=True,
        max_length=256,
    )
    return {"input_ids": tokenized["input_ids"], "attention_mask": tokenized["attention_mask"], "labels": row["label"]}

In [31]:
def tokenize_custom(row, tokenizer):
    question = tokenizer(row["prompt"], padding="max_length", truncation=True, max_length=256)
    options = [tokenizer(row[option], padding="max_length", truncation=True, max_length=256) for option in ["A", "B", "C", "D", "E"]]
    result = {
        "question_ids": question["input_ids"],
        "question_mask": question["attention_mask"],
        "option_ids": [option["input_ids"] for option in options],
        "option_mask": [option["attention_mask"] for option in options],
    }
    result["labels"] = row["label"]
    return result

In [32]:
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)
torch.cuda.manual_seed_all(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_index, validation_index = next(splitter.split(train, groups=train["prompt"]))
train_data = train.iloc[train_index]
validation_data = train.iloc[validation_index]

## BERT

In [33]:
bert_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
bert_train_dataset = dataset_from(train_data, 
                                  lambda row: tokenize_pretrained(row, bert_tokenizer), ["input_ids", "attention_mask", "labels"])
bert_val_dataset = dataset_from(validation_data, 
                                lambda row: tokenize_pretrained(row, bert_tokenizer), ["input_ids", "attention_mask", "labels"])
bert_training_args = build_training_args(output_dir="./mcq_model/bert", run_name="bert")
bert_trainer = build_pretrained_trainer(get_bert_model().to(device), 
                                        bert_train_dataset, 
                                        bert_val_dataset, 
                                        bert_training_args, 
                                        map3_metric)
bert_trainer.train()

Map: 100%|██████████| 1453/1453 [00:01<00:00, 1000.49 examples/s]
Map: 100%|██████████| 364/364 [00:00<00:00, 948.81 examples/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5381.13it/s]
[transformers] BertForMultipleChoice LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.33s/it]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.16s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.18s/it]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s]
Writing model shards: 100%|██████████| 1/1 [00:06<00:00,  6.26s/it]
[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=910, training_loss=0.5693897480493063, metrics={'train_runtime': 456.0171, 'train_samples_per_second': 15.931, 'train_steps_per_second': 1.996, 'total_flos': 4778711636467200.0, 'train_loss': 0.5693897480493063, 'epoch': 5.0})

## RoBERTa

In [34]:
roberta_tokenizer = AutoTokenizer.from_pretrained("FacebookAI/roberta-base")
roberta_train_dataset = dataset_from(train_data, 
                                     lambda row: tokenize_pretrained(row, roberta_tokenizer), ["input_ids", "attention_mask", "labels"])
roberta_val_dataset = dataset_from(validation_data, 
                                   lambda row: tokenize_pretrained(row, roberta_tokenizer), ["input_ids", "attention_mask", "labels"])
roberta_training_args = build_training_args(output_dir="./mcq_model/roberta", run_name="roberta")
roberta_trainer = build_pretrained_trainer(get_roberta_model().to(device), 
                                           roberta_train_dataset, 
                                           roberta_val_dataset, 
                                           roberta_training_args, 
                                           map3_metric)

Map: 100%|██████████| 1453/1453 [00:01<00:00, 832.23 examples/s]
Map: 100%|██████████| 364/364 [00:00<00:00, 793.42 examples/s]
Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1084.82it/s]
[transformers] RobertaForMultipleChoice LOAD REPORT from: FacebookAI/roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.bias             | MISSING    |
roberta.pooler.dense.weight | MISSING    |
classifier.weight           | MISSING    |
roberta.pooler.dense.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [35]:
roberta_trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.71it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.23it/s]

TrainOutput(global_step=910, training_loss=0.48796541327303583, metrics={'train_runtime': 5686.5576, 'train_samples_per_second': 1.278, 'train_steps_per_second': 0.16, 'total_flos': 4778711636467200.0, 'train_loss': 0.48796541327303583, 'epoch': 5.0})

## Custom bi-encoder

In [38]:
batch_size = 16
epochs = 30
custom_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
custom_train_dataset = dataset_from(train_data, 
                                    lambda row: tokenize_custom(row, custom_tokenizer), ["question_ids", "question_mask", "option_ids", "option_mask", "labels"])
custom_val_dataset = dataset_from(validation_data, 
                                  lambda row: tokenize_custom(row, custom_tokenizer), ["question_ids", "question_mask", "option_ids", "option_mask", "labels"])
train_loader = DataLoader(custom_train_dataset, batch_size=batch_size, shuffle=True)
validation_loader = DataLoader(custom_val_dataset, batch_size=batch_size)

Map: 100%|██████████| 1453/1453 [00:01<00:00, 1067.70 examples/s]
Map: 100%|██████████| 364/364 [00:00<00:00, 966.11 examples/s]

In [39]:
custom_model = MCQBiEncoder(vocab_size=custom_tokenizer.vocab_size, dropout=0.1, temperature=0.07).to(device)
print(custom_model)
optimizer = optim.AdamW(custom_model.parameters(), lr=1e-4)

MCQBiEncoder(
  (encoder): TransformerEncoder(
    (embedding): Embedding(30522, 256, padding_idx=0)
    (position): PositionalEncoding()
    (dropout): Dropout(p=0.1, inplace=False)
    (encoder): TransformerEncoder(
      (layers): ModuleList(
        (0-3): 4 x TransformerEncoderLayer(
          (self_attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
          )
          (linear1): Linear(in_features=256, out_features=1024, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
          (linear2): Linear(in_features=1024, out_features=256, bias=True)
          (norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True, bias=True)
          (norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True, bias=True)
          (dropout1): Dropout(p=0.1, inplace=False)
          (dropout2): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
)

In [40]:
custom_trainer = MCQTrainer(custom_model, 
                            optimizer, 
                            nn.CrossEntropyLoss(), 
                            device, 
                            build_custom_scheduler(optimizer, epochs), 
                            wandb_run,
                            "custom_model.pt")

In [41]:
custom_trainer.fit(train_loader, validation_loader, epochs)

Epoch 1/30

100%|██████████| 91/91 [00:15<00:00,  5.70it/s]
  0%|          | 0/23 [00:00<?, ?it/s]C:\Users\bires\AppData\Roaming\Python\Python314\site-packages\torch\nn\modules\transformer.py:529: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. We recommend specifying layout=torch.jagged when constructing a nested tensor, as this layout receives active development, has better operator coverage, and works with torch.compile. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\NestedTensorImpl.cpp:181.)
  output = torch._nested_tensor_from_mask(
100%|██████████| 23/23 [00:00<00:00, 33.18it/s]

Train Loss : 1.5170

Val Loss   : 1.1599
Accuracy   : 0.4918
MAP@3      : 0.6438

Saved best model

Epoch 2/30

100%|██████████| 91/91 [00:15<00:00,  5.70it/s]
100%|██████████| 23/23 [00:00<00:00, 40.55it/s]

Train Loss : 1.0345

Val Loss   : 0.6765
Accuracy   : 0.7390
MAP@3      : 0.8356

Saved best model

Epoch 3/30

100%|██████████| 91/91 [00:16<00:00,  5.67it/s]
100%|██████████| 23/23 [00:00<00:00, 39.73it/s]

Train Loss : 0.6800

Val Loss   : 0.3854
Accuracy   : 0.8929
MAP@3      : 0.9382

Saved best model

Epoch 4/30

100%|██████████| 91/91 [00:16<00:00,  5.68it/s]
100%|██████████| 23/23 [00:00<00:00, 40.01it/s]

Train Loss : 0.4938

Val Loss   : 0.2577
Accuracy   : 0.9368
MAP@3      : 0.9647

Saved best model

Epoch 5/30

100%|██████████| 91/91 [00:15<00:00,  5.71it/s]
100%|██████████| 23/23 [00:00<00:00, 39.83it/s]

Train Loss : 0.3749

Val Loss   : 0.1412
Accuracy   : 0.9780
MAP@3      : 0.9876

Saved best model

Epoch 6/30

100%|██████████| 91/91 [00:16<00:00,  5.58it/s]
100%|██████████| 23/23 [00:00<00:00, 36.89it/s]

Train Loss : 0.2337

Val Loss   : 0.0895
Accuracy   : 0.9863
MAP@3      : 0.9918

Saved best model

Epoch 7/30

100%|██████████| 91/91 [00:16<00:00,  5.44it/s]
100%|██████████| 23/23 [00:00<00:00, 38.15it/s]

Train Loss : 0.1741

Val Loss   : 0.0410
Accuracy   : 0.9973
MAP@3      : 0.9986

Saved best model

Epoch 8/30

100%|██████████| 91/91 [00:16<00:00,  5.43it/s]
100%|██████████| 23/23 [00:00<00:00, 37.84it/s]

Train Loss : 0.1188

Val Loss   : 0.0405
Accuracy   : 0.9918
MAP@3      : 0.9954


Epoch 9/30

100%|██████████| 91/91 [00:17<00:00,  5.27it/s]
100%|██████████| 23/23 [00:00<00:00, 29.19it/s]

Train Loss : 0.0987

Val Loss   : 0.0304
Accuracy   : 0.9945
MAP@3      : 0.9973


Epoch 10/30

100%|██████████| 91/91 [00:16<00:00,  5.41it/s]
100%|██████████| 23/23 [00:00<00:00, 31.34it/s]

Train Loss : 0.0662

Val Loss   : 0.0203
Accuracy   : 0.9945
MAP@3      : 0.9973


Epoch 11/30

100%|██████████| 91/91 [00:16<00:00,  5.37it/s]
100%|██████████| 23/23 [00:00<00:00, 31.99it/s]

Train Loss : 0.0509

Val Loss   : 0.0199
Accuracy   : 0.9945
MAP@3      : 0.9973


Epoch 12/30

100%|██████████| 91/91 [00:16<00:00,  5.51it/s]
100%|██████████| 23/23 [00:00<00:00, 31.32it/s]

Train Loss : 0.0382

Val Loss   : 0.0121
Accuracy   : 0.9945
MAP@3      : 0.9973


Epoch 13/30

100%|██████████| 91/91 [00:16<00:00,  5.48it/s]
100%|██████████| 23/23 [00:00<00:00, 32.65it/s]

Train Loss : 0.0265

Val Loss   : 0.0073
Accuracy   : 1.0000
MAP@3      : 1.0000

Saved best model

Epoch 14/30

100%|██████████| 91/91 [00:16<00:00,  5.48it/s]
100%|██████████| 23/23 [00:00<00:00, 32.97it/s]

Train Loss : 0.0235

Val Loss   : 0.0050
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 15/30

100%|██████████| 91/91 [00:16<00:00,  5.45it/s]
100%|██████████| 23/23 [00:00<00:00, 33.52it/s]

Train Loss : 0.0286

Val Loss   : 0.0052
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 16/30

100%|██████████| 91/91 [00:16<00:00,  5.46it/s]
100%|██████████| 23/23 [00:00<00:00, 32.28it/s]

Train Loss : 0.0179

Val Loss   : 0.0054
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 17/30

100%|██████████| 91/91 [00:16<00:00,  5.45it/s]
100%|██████████| 23/23 [00:00<00:00, 25.20it/s]

Train Loss : 0.0187

Val Loss   : 0.0035
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 18/30

100%|██████████| 91/91 [00:16<00:00,  5.44it/s]
100%|██████████| 23/23 [00:00<00:00, 34.11it/s]

Train Loss : 0.0289

Val Loss   : 0.0031
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 19/30

100%|██████████| 91/91 [00:16<00:00,  5.49it/s]
100%|██████████| 23/23 [00:00<00:00, 33.15it/s]

Train Loss : 0.0180

Val Loss   : 0.0026
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 20/30

100%|██████████| 91/91 [00:16<00:00,  5.49it/s]
100%|██████████| 23/23 [00:00<00:00, 31.66it/s]

Train Loss : 0.0069

Val Loss   : 0.0023
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 21/30

100%|██████████| 91/91 [00:16<00:00,  5.48it/s]
100%|██████████| 23/23 [00:00<00:00, 32.34it/s]

Train Loss : 0.0101

Val Loss   : 0.0030
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 22/30

100%|██████████| 91/91 [00:16<00:00,  5.49it/s]
100%|██████████| 23/23 [00:00<00:00, 30.54it/s]

Train Loss : 0.0140

Val Loss   : 0.0025
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 23/30

100%|██████████| 91/91 [00:16<00:00,  5.47it/s]
100%|██████████| 23/23 [00:00<00:00, 34.27it/s]

Train Loss : 0.0221

Val Loss   : 0.0029
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 24/30

100%|██████████| 91/91 [00:16<00:00,  5.48it/s]
100%|██████████| 23/23 [00:00<00:00, 33.47it/s]

Train Loss : 0.0141

Val Loss   : 0.0022
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 25/30

100%|██████████| 91/91 [00:16<00:00,  5.43it/s]
100%|██████████| 23/23 [00:00<00:00, 31.51it/s]

Train Loss : 0.0105

Val Loss   : 0.0024
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 26/30

100%|██████████| 91/91 [00:16<00:00,  5.48it/s]
100%|██████████| 23/23 [00:00<00:00, 31.29it/s]

Train Loss : 0.0107

Val Loss   : 0.0019
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 27/30

100%|██████████| 91/91 [00:16<00:00,  5.45it/s]
100%|██████████| 23/23 [00:00<00:00, 29.46it/s]

Train Loss : 0.0109

Val Loss   : 0.0019
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 28/30

100%|██████████| 91/91 [00:17<00:00,  5.16it/s]
100%|██████████| 23/23 [00:00<00:00, 31.97it/s]

Train Loss : 0.0070

Val Loss   : 0.0018
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 29/30

100%|██████████| 91/91 [00:16<00:00,  5.40it/s]
100%|██████████| 23/23 [00:00<00:00, 32.66it/s]

Train Loss : 0.0103

Val Loss   : 0.0018
Accuracy   : 1.0000
MAP@3      : 1.0000


Epoch 30/30

100%|██████████| 91/91 [00:16<00:00,  5.42it/s]
100%|██████████| 23/23 [00:00<00:00, 32.94it/s]

Train Loss : 0.0166

Val Loss   : 0.0018
Accuracy   : 1.0000
MAP@3      : 1.0000

## Submission

In [ ]:
custom_test_dataset = dataset_from(test.assign(label=0), 
                                   lambda row: tokenize_custom(row, custom_tokenizer), 
                                   ["question_ids", "question_mask", "option_ids", "option_mask"])
test_loader = DataLoader(custom_test_dataset, batch_size=batch_size)
submission = generate_submission(test_loader, custom_trainer, sampleSubmissionPath, "/kaggle/working/submission.csv")
wandb_run.finish()
submission.head()

Map: 100%|██████████| 500/500 [00:00<00:00, 744.14 examples/s]
100%|██████████| 32/32 [00:01<00:00, 29.92it/s]

OSError: Cannot save file into a non-existent directory: '\kaggle\working'